# Generated by Django 3.2.9 on 2022-07-19 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0005_productmodel_prdct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='catogoryModel',
        ),
    ]
