# Generated by Django 3.2.9 on 2022-07-24 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0008_bookmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='book_date',
            field=models.DateField(default=1),
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='book_time',
            field=models.TimeField(default=1),
        ),
    ]
