# Generated by Django 3.2.9 on 2022-07-24 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0009_auto_20220724_0128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmodel',
            name='book_date',
        ),
        migrations.RemoveField(
            model_name='bookmodel',
            name='book_time',
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
