# Generated by Django 3.2.9 on 2022-07-24 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0010_auto_20220724_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmodel',
            name='date',
        ),
    ]
